server:
  port: 8761
  tomcat:
    basedir: .
    accesslog:
      buffered: false
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss.SSS}t %h %A %l %user \"%r\" %s %b %D"
      prefix: access
      rename-on-rotate: false
      request-attributes-enabled: true
      rotate: true
      suffix: .log

spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: default
  application:
    name: myflx-discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/